local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader><leader>', builtin.find_files, {})
vim.keymap.set('n', '<leader>a', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") });
end)  
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', 'C-a', builtin.live_grep, {})
vim.keymap.set('n', ';', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>f;', ':lua require\'telescope.builtin\'.current_buffer_fuzzy_find()<CR>', {})
